---
driver:
  name: docker
  hostname: fluentbit.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  # salt_bootstrap_options: -P git
  require_chef: false
  log_level: error
  formula: fluentbit
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - linux.system.repo
        - fluentbit
  pillars:
    top.sls:
      base:
        "*":
          - linux
          - fluentbit
    linux.sls: {}

verifier:
  name: inspec
  sudo: true

<% platform = ENV['PLATFORM'] || 'xenial' %>
<% dist_version = platform.split(/:|-/)[2] %>
platforms:
  <% if %w(ubuntu).include? dist_version %>
  - name: <%= ENV['PLATFORM'] || 'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%= ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu
  <% else %>
  - name: <%= ENV['PLATFORM'] || 'saltstack-centos-7-salt-stable' %>
    driver_config:
      image: <%= ENV['PLATFORM'] || 'epcim/salt:saltstack-centos-7-salt-stable'%>
      platform: centos
      privileged: True
      run_command: /usr/sbin/init
  <% end %>
    provisioner:
      init_environment: |
        sudo yum install -y git || sudo apt-get install -y git || true
      pillars:
        linux.sls:
          linux:
            system:
              enabled: true
              repo:
                fluentbit:
                  <% if %w(ubuntu).include? dist_version %>
                  architectures: amd64
                  key_url: "http://packages.fluentbit.io/fluentbit.key"
                  source: "deb [arch=amd64] http://packages.fluentbit.io/ubuntu <%= platform.split(/:|-/)[3]%> main"
                  clean_file: true
                  <% else %>
                  source: "http://packages.fluentbit.io/centos/7"
                  gpgkey: "http://packages.fluentbit.io/fluentbit.key"
                  gpgcheck: true
                  <% end %>

suites:
  - name: default
    provisioner:
      pillars-from-files:
        fluentbit.sls: tests/pillar/default.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
