classes:
- service.fluentbit.config

parameters:
  fluentbit:
    config:
      parser:
        haproxy.conf:
          haproxy:
            format: regex
            # https://regex101.com/r/ThV0ty
            regex: '^(?<log_time>[^ +][-:0-9TZ]+|[[:upper:]][[:lower:]]{2}[ -:+0-9TZ]*)([^ ][+0:]+|\s+)(\s*)(?<host>[^ ][-\w]+)(\s*)(?<service>[^ ][-\[\]\d\w]+):\s+(?<message>[^ ].*)$'
            time_key: log_time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'Off'
    service:
      parsers_file:
        - 'parser_haproxy.conf'
