classes:
- service.fluentbit.config

parameters:
  fluentbit:
    config:
      parser:
        nova.conf:
          nova-api:
            format: regex
            # https://regex101.com/r/NYogHF/1/
            regex: '^(?P<time>[^ ][-\d:]*\ [.\d:]*)\s+(?P<pid>[^ ]\d+)\s+(?P<severity>[^ ]\w+)\s+(?P<component>[^ ][.-_\w]+)\s+(\[((?<req>[^ ][-\w]+)){0,1}(\s+(?<res>[^ ][-\w]+)){0,1}(\s+(?<res2>[^ ][-\w]+)){0,1}[- ]*\]){0,1}\s+(?<from>[^ ][,.\d]*)\s+\"(?<message>.*)$'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
          nova-conductor:
            format: regex
            # https://regex101.com/r/N76dUJ/1/
            regex: '^(?P<time>[^ ][-\d:]*\ [.\d:]*)\s+(?P<pid>[^ ]\d+)\s+(?P<severity>[^ ]\w+)\s+(?P<component>[^ ][.-_\w]+)\s+(\[((?<req>[^ ][-\w]+)){0,1}(\s+(?<res>[^ ][-\w]+)){0,1}(\s+(?<res2>[^ ][-\w]+)){0,1}[- ]*\]){0,1}(?<message>.*)$'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
    service:
      parsers_file:
        - 'parser_nova.conf'
