classes:
- service.fluentbit.config

parameters:
  fluentbit:
    config:
      parser:
        nova.conf:
          nova-api:
            format: regex
            # http://rubular.com/r/7zgjN93NLS
            # http://regex101.com/r/NYogHF/1/
            regex: '^(?<time>[^ ][-.\d\+:T]+[ ]*[.:\d]*)\s+(?<pid>[^ ]\d+)\s+(?<severity>[^ ][.-_\w]+)\s+(?<component>[^ ][.-_\w]+)(\s+\[(-|(?<req_id>[^ ][-\w]*) (?<req_user>[^ ][-\w]*) (?<req_project>[^ ][-\w]*) (?<req_domain>[^ ][-\w]*) (?<req_user_domain>[^ ][-\w]*) (?<req_project_domain>[^ ][-\w]*))\]){0,1}\s+(?<message>.*)$'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
          nova-conductor:
            format: regex
            regex: '^(?<time>[^ ][-.\d\+:T]+[ ]*[.:\d]*)\s+(?<pid>[^ ]\d+)\s+(?<severity>[^ ][.-_\w]+)\s+(?<component>[^ ][.-_\w]+)(\s+\[(-|(?<req_id>[^ ][-\w]*) (?<req_user>[^ ][-\w]*) (?<req_project>[^ ][-\w]*) (?<req_domain>[^ ][-\w]*) (?<req_user_domain>[^ ][-\w]*) (?<req_project_domain>[^ ][-\w]*))\]){0,1}\s+(?<message>.*)$'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
    service:
      parsers_file:
        - 'parser_nova.conf'
