parameters:
  fluentbit:
    config:
      parser:
        pacemaker.conf:
          pacemaker:
            format: regex
            # https://regex101.com/r/6yzXO1/1
            regex: '^\s*(?<time>[^ ]* {1,2}[^ ]* [^ ]*) \[(?<pid>\d+)\] (?<macid>[\-\w]*)\s*(?<component>\w*):\s+(?<severity>\w+):\s+(?<action>\w+):\s+(?<action_status>\w+) (?<mesage>[^\(]*) (\((?<meta>.*)\))$'
            time_key: time
            time_format: '%b %d %H:%M:%S'
              # Sep 17 09:43:44
            time_keep: 'On'
            types:
              - 'pid:integer'
    service:
      parsers_file:
        - 'parser_pacemaker.conf'
