classes:
- service.fluentbit.config

parameters:
  fluentbit:
    config:
      parser:
        pacemaker.conf:
          pacemaker:
            format: regex
            # https://regex101.com/r/6yzXO1
            regex: '^\s*(?<time>[^ ]* {1,2}[^ ]* [^ ]*) \[(?<pid>\d+)\] (?<macid>[\-\w]*)\s*(?<component>\w*):\s+(?<severity>\w+):\s+(?<action>\w+):\s+(?<action_status>\w+) (?<mesage>[^\(]*) (\((?<meta>.*)\))$'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
            types:
              - 'pid:integer'
    service:
      parsers_file:
        - 'parser_pacemaker.conf'
