parameters:
  fluentbit:
    config:
      parser:
        postgresql_statements.conf:
          postgresql_statements:
            # https://regex101.com/r/sgk3sR/1
            format: regex
            regex: '^STATEMENT:\s*(?<statement>[^\n]*)(\nERROR:\s*(?<error>[^\n]*))(\nDETAIL:\s*(?<detail>[^\n]*))$'
            time_keep: 'On'
    service:
      parsers_file:
        - 'parser_postgresql_statements.conf'
