classes:
- service.fluentbit.config

parameters:
  fluentbit:
    config:
      parser:
        rabbitmq.conf:
          rabbitmq:
            format: regex
            # https://regex101.com/r/
            regex: '^=(?<severity>[^ ]\w+)\s+REPORT[=\s]*(?<time>[^ =]*)\s*[=]*\n(?<message>.*?(?=\R\R|\z))'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
            types:
              - 'serverity:string'
              - 'message:string'
          rabbitmq_f:
            format: regex
            # https://regex101.com/r/
            # http://rubular.com/r/eX8UjwGLEI
            regex: '^=(?<severity>[^ ]\w+)\s+REPORT[=\s]*(?<time>[^ =][-:.\d\w]+)[\s=]+$'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
            types:
              - 'serverity:string'
          rabbitmq_1:
            format: regex
            regex: '^(?<message>.*?(?=\R\R|\z))$'
            types:
              - 'message:string'
    service:
      parsers_file:
        - 'parser_rabbitmq.conf'
