classes:
- service.fluentbit.config

parameters:
  fluentbit:
    config:
      parser:
        rabbitmq.conf:
          rabbitmq:
            format: regex
            # https://regex101.com/r/zGYU05/2
            regex: '^=(?<severity>[^ ].*)\s+REPORT[=\s]*(?<time>[^ =]*)\s*[=]*\n(?<message>(?s)^(.*?)(?:(?:\r*\n){2}))'
            time_key: time
            time_format: ${_param:fluentbit_config_timeformat}
            time_keep: 'On'
            types:
              - 'component:string'
              - 'serverity:string'
              - 'message:string'
    service:
      parsers_file:
        - 'parser_rabbitmq.conf'
