classes:
- service.fluentbit.config.parser.haproxy
parameters:
  fluentbit:
    config:
      input:
        haproxy.conf:
          tail:
            parser: haproxy
            path: /var/log/haproxy.log*
            path_key: On
            DB: /tmp/haproxy.flb.db
            exclude_path: '*.gz,*.xz'
            multiline_flush: 4
            multiline: On
            chunk_size: 32k
            buffer_max_size: 64k
            tag: haproxy
      service:
        td-agent-bit.conf:
          - '@INCLUDE input_haproxy.conf'

