classes:
- service.fluentbit.config
- service.fluentbit.config.parser.haproxy

parameters:
  fluentbit:
    config:
      input:
        haproxy.conf:
          tail:
            parser: haproxy
            path: ${_param:fluentbit_config_syslogpath}/haproxy.log*
            path_key: path
            DB: /var/lib/fluentbit/haproxy.flb.db
            exclude_path: '*.gz,*.xz'
            #multiline_flush: 4
            multiline: Off
            chunk_size: 32k
            buffer_max_size: 512k
            tag: haproxy
      service:
        td-agent-bit.conf:
          - '@INCLUDE input_haproxy.conf'

