classes:
- service.fluentbit.config
- service.fluentbit.config.parser.pacemaker

parameters:
  fluentbit:
    config:
      input:
        pacemaker.conf:
          tail:
            parser: pacemaker
            path: ${_param:fluentbit_config_syslogpath}/pacemaker.log*
            path_key: path
            DB: /var/lib/fluentbit/pacemaker.flb.db
            exclude_path: '*.gz,*.xz'
            #multiline_flush: 4
            multiline: Off
            chunk_size: 32k
            buffer_max_size: 512k
            tag: pacemaker
      service:
        td-agent-bit.conf:
          - '@INCLUDE input_pacemaker.conf'

