classes:
- service.fluentbit.config
- service.fluentbit.config.parser.postgresql_statements

parameters:
  fluentbit:
    config:
      input:
        postgresql.conf:
          tail:
            #multiline: 'Off'
            #parser: postgresql_statements
            multiline: 'On'
            parser_firstline: postgresql_statement_s
            parser_2: postgresql_statement_e
            parser_3: postgresql_statement_d
            ##
            path: ${_param:fluentbit_config_syslogpath}/postgresql.log*
            path_key: path
            DB: /tmp/postgresql.flb.db
            exclude_path: '*.gz,*.xz'
            multiline_flush: 4
            buffer_chunk_size: 4k
            buffer_max_size: 64k
            tag: postgresql.statements
      service:
        td-agent-bit.conf:
          - '@INCLUDE input_postgresql.conf'

