classes:
- service.fluentbit.config
- service.fluentbit.config.parser.postgresql_statements

parameters:
  fluentbit:
    config:
      input:
        postgresql_statements.conf:
          tail:
            parser: postgresql_statements
            path: ${_param:fluentbit_config_syslogpath}/postgresql.log*
            path_key: path
            DB: /tmp/postgresql.flb.db
            exclude_path: '*.gz,*.xz'
            multiline_flush: 4
            multiline: Off
            chunk_size: 32k
            buffer_max_size: 64k
            tag: postgresql.statements
      service:
        td-agent-bit.conf:
          - '@INCLUDE input_postgresql_statements.conf'

