classes:
- service.fluentbit.config
- service.fluentbit.config.parser.rabbitmq

parameters:
  fluentbit:
    config:
      input:
        rabbitmq.conf:
          tail:
            parser: rabbitmq
            path: ${_param:fluentbit_config_syslogpath}/rabbitmq/rabbit*
            path_key: path
            DB: /tmp/rabbitmq.flb.db
            exclude_path: '*.gz,*.xz'
            multiline_flush: 4
            multiline: Off
            chunk_size: 32k
            buffer_max_size: 64k
            tag: rabbitmq
      service:
        td-agent-bit.conf:
          - '@INCLUDE input_rabbitmq.conf'

